### Fetch All / Search customer
GET http://localhost:3000/api/customers

### Create Customer
POST http://localhost:3000/api/customers HTTP/1.1
Content-Type: application/json

{
    "name": "Craig",
    "email": "craig@hotmail.gov"
}

### Get Customer By ID
GET http://localhost:3000/api/customers/8